name: Cut Release
on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'put commit sha here'
        required: true
env:
  CCI_TOKEN: ${{ secrets.CCI_TOKEN }}

jobs:
  cut-release:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3
      run: |
        